name: Build PhpStorm plugin

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install tools
        run: sudo apt update && sudo apt install jq xmlstarlet zip

      - name: Setup PHP
        uses: shivammathur/setup-php@2.12.0
        with:
          php-version: 8.0
 
      - name: Get actual tag name
        id: tag-name
        run: echo ::set-output name=TAG_NAME::$(echo "${{ github.ref }}" | sed 's{^refs/tags/{{')

      - name: Download PocketMine-MP.phar
        run: curl -f -L ${{ github.server_url }}/${{ github.repository }}/releases/download/${{ steps.tag-name.outputs.TAG_NAME }}/PocketMine-MP.phar -o PocketMine-MP.phar
 
      - name: Extract PocketMine-MP.phar
        run: phar extract -f PocketMine-MP.phar stage/library/PocketMine-MP

      - name: Generate HTML changelog
        id: changelog
        run: |
          CHANGELOG_MD=$(curl -f https://api.github.com/repos/pmmp/PocketMine-MP/releases/tags/${{ steps.tag-name.outputs.TAG_NAME }} | jq .body -r)
          echo ::set-output name=CHANGELOG:$(curl -f https://api.github.com/markdown -X POST -d "$(jq -n --arg body "$CHANGELOG_MD" '{"text":$body,"mode":"gfm","context":"pmmp/PocketMine-MP"}')")

      - name: Generate plugin.xml
        run: |
          curl -f -o tmp.xml https://gist.githubusercontent.com/SOF3/5cc4d0c67c7094d8599b846be1e5f99e/raw/65f7a3f959ca60d90ad2bcddd183109262703dcb/default-plugin.xml
          xmlstarlet ed -u /idea-plugin/version -v ${{ steps.tag-name.outputs.TAG_NAME }} tmp.xml > tmp2.xml
          mkdir -p stage/META-INF/
          xmlstarlet ed -u /idea-plugin/change-notes -v "${{ steps.changelog.outputs.CHANGELOG }}" tmp2.xml > stage/META-INF/plugin.xml

      - name: Package plugin
        run: |
          cd stage
          zip -qr ../plugin.jar .

      - name: Store plugin.jar artifact
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: plugin
          path: plugin.jar

